### ISSUE TITLE
Hardware connection

### ISSUE THREAD

**Issue by caiosignor** [lamik/MAX30102_STM32_HAL#1]
Hi.
Can you tell me the hardware connection to reproduce the code?

**Comment by lamik** [comment]
Sure. You can find it on my blog: https://msalamon.pl/palec-mi-pulsuje-pulsometr-max30102-pod-kontrola-stm32/

Hope polish language won't be a problem. There is a schematic for Nucleo connection.

**Comment by caiosignor** [comment]
Nice. Thanks!!
